Django/myscrumy/myscrumy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('samsonadejoroscrumy/', include('samsonadejoroscrumy.urls')),
    path('admin/', admin.site.urls),
]

Django/myscrumy/samsonadejoroscrumy/urls.py
from django.urls import path, include
from django.conf.urls import url,include
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import obtain_jwt_token

app_name = 'samsonadejoroscrumy'
router = DefaultRouter()
#router.register(r'users', views.UserViewSet, basename='users')
router.register(r'scrumusers', views.ScrumUserViewSet, basename='scrumusers')
router.register(r'goals', views.ScrumGoalViewSet, basename='scrumgoals')

urlpatterns = [
    path('', views.index, name='index'),
    #path('movegoal/<int:goal_id>/', views.move_goal, name='movegoal'),
    #path('home/', views.home, name='home'),
    #path('addgoal/', views.add_goal, name='add_goal'),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path('success/', views.success_page, name='success'),
    #path('goalsuccess/', views.success_goal, name='goalsuccess'),
    #path('error/', views.error, name='error'),
    #path('movegoalsuccess/', views.move_goal_success, name='movegoalsuccess'),
    #path('errors/', views.errors, name='errors'),
    path('api/', include((router.urls, 'app_name'))),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', obtain_jwt_token),
]

Django/myscrumy/samsonadejoroscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms


# Create your models here.

class ScrumUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=30)

    def __str__(self):
        return (self.nickname)

    class Meta:
        verbose_name_plural = 'Scrum Users'
        ordering = ['nickname']

class GoalStatus(models.Model):
    status_name = models.CharField(max_length=200)

    def __str__(self):
        return self.status_name



class ScrumyGoals(models.Model):
    visible = models.BooleanField(default=True)
    moveable = models.BooleanField(default=True)
    goal_name= models.CharField(max_length=200)
    goal_id= models.CharField(max_length=100)
    created_by = models.CharField(max_length=200)
    moved_by = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)
    user=models.ForeignKey(ScrumUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.goal_id

    class Meta:
        ordering = ['-goal_id']
        verbose_name_plural = "Scrumy Goals"




class ScrumProjectRole(models.Model):
    role = models.CharField(max_length=20)
    user = models.ForeignKey(ScrumUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.role






class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']


class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'goal_id']


class AddGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'goal_status']


class WeekOnlyAddGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name']


class DevMoveGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class AdminChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class AdminChangeForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[1:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class OwnerChangeForm(forms.ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']


class QAChangegoal(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[::1][:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class QAChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('-id')[:4][::4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']


class QAMoveForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[1:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']

Django/myscrumy/samsonadejoroscrumy/views.py
from samsonadejoroscrumy.models import GoalStatus, ScrumyGoals
from django.contrib.auth.models import User, Group, Permission
from .models import SignUpForm, CreateGoalForm, AddGoalForm, WeekOnlyAddGoalForm, QAChangegoal, DevMoveGoalForm, \
    AdminChangeGoalForm, QAChangeGoalForm, QAMoveForm, AdminChangeForm, OwnerChangeForm, ScrumUser, ScrumProjectRole
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import authenticate, login
from django.template import loader
from django.utils.datastructures import MultiValueDictKeyError
# from django.conf import settings
from django.shortcuts import render, redirect
# from django.contrib.auth.decorators import login_required
from random import *
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from rest_framework import viewsets, status, views, permissions
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated

from .serializers import *
from .models import ScrumyGoals, GoalStatus

content_type_scrumygoals = ContentType.objects.get_for_model(ScrumyGoals)
content_type_goalstatus = ContentType.objects.get_for_model(GoalStatus)

developergroup = Group.objects.get(name='Developer')
admingroup = Group.objects.get(name='Admin')
qualityassurancegroup = Group.objects.get(name='Quality Assurance')
ownergroup = Group.objects.get(name='Owner')
verifygoal = GoalStatus.objects.get(status_name="Verify Goal")

def move_goal(request, goal_id, to_id):
    if request.user.is_authenticated:
        goal_item = ScrumyGoals.objects.get(id=goal_id)
        group_name = request.user.groups.all()[0].name
        from_allowed = []
        to_allowed = []

        if group_name == 'Developer':
            if request.user != goal_item.user.user:
                messages.error(request, 'Permission Denied: Unauthorized Moving of Goal')
                return HttpResponseRedirect(reverse('samsonadejoroscrumy:scrumboard'))
        if group_name == 'Owner':
            from_allowed = [0, 1, 2, 3]
            to_allowed = [0, 1, 2, 3]
        elif group_name == 'Admin':
            from_allowed = [1, 2]
            to_allowed = [1, 2]
        elif group_name == 'Developer':
            from_allowed = [0, 1]
            to_allowed = [0, 1]
        elif group_name == 'Quality Analyst':
            from_allowed = [2, 3]
            to_allowed = [2, 3]

        if (goal_item.status in from_allowed) and (to_id in to_allowed):
            goal_item.status = to_id
        elif group == 'Quality Analyst' and goal_item.status == 2 and to_id == 0:
            goal_item.status = to_id
        else:
            messages.error(request, 'Permission Denied: Unauthorized Moving of Goal')
            return HttpResponseRedirect(reverse('samsonadejoroscrumy:scrumboard'))
        goal_item.save()
        messages.success(request, 'Goal moved successfully')
        return HttpResponseRedirect(reverse('samsonadejoroscrumy:scrumboard'))
    else:
        messages.error(request, 'Error: Please login')
        return HttpResponseRedirect(reverse('login'))

'''
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def create(self, request):
        username = request.data['username']
        password = request.data['password']

        login_user = authenticate(request, username=username, password=password)
        if login_user is not None:
            return JsonResponse({'exit': 0, 'message': 'Welcome to your Scrum Board', 'role': login_user.groups.all()[0].name,'data': filtered_users()})
        else: 
            return JsonResponse({'exit': 1, 'message': 'Error: Invalid Credentials'})

'''
# class ScrumUserViewSet(viewsets.ModelViewSet):
#     queryset = ScrumyGoals.objects.all()
#     serializer_class = ScrumUserSerializer

#     def create(self, request):
#         user, created = User.objects.get_or_create(username=request.data['username'])
#         if created:

#             group = Group.objects.get(name=request.data['usertype'])
#             group.user_set.add(user)
#             user.save()
#             scrum_user = ScrumUser(user=user,
#                                    fullname=request.data['full_name'],
#                                    age=request.data['age'])
#             scrum_user.save()
#             return JsonResponse({'message': 'User created successfully'})
#         else:
#             return JsonResponse({'message': 'Error: Username already exist'})
def filtered_users():
    users = ScrumUserSerializer(ScrumUser.objects.all(), many=True).data

    for user in users:
        user['scrumygoals_set'] = [x for x in user['scrumygoals_set']
         if x['visible'] == True]
    return users

'''
class ScrumUserViewSet(viewsets.ModelViewSet):
    queryset = ScrumUser.objects.all()
    serializer_class = ScrumUserSerializer
    def create(self,request):
        user, created = User.objects.get_or_create(username=request.data['username'], email=request.data['email'])
        if created:
            scrum_user = ScrumUser(user=user, nickname=request.data['full_name'])
            scrum_user.save()
            if request.data['usertype'] == 'Owner':
                scrum_project_role = ScrumProjectRole(role="Owner", user=scrum_user)
                scrum_project_role.save()

            user.set_password(request.data['password'])
            user.save()
            return JsonResponse({'message': 'User Created Successfully.'})
        else:
            return JsonResponse({'message': 'Error: User with that e-mail already exists.'})
'''
class ScrumUserViewSet(viewsets.ModelViewSet):
    queryset = ScrumUser.objects.all()
    serializer_class = ScrumUserSerializer

    def create(self, request):
        password = request.data['password']
        confirmpassword = request.data['pass_auth']
        role = request.data['usertype']
        fullname = request.data['full_name']
        username = request.data['username']

        if password == '' and role == '' and fullname == '' and username == '':
            return JsonResponse({'message': 'Error: All fields are required.'})
        if password != confirmpassword:
            return JsonResponse({'message': 'Error: Password Do not match.'})
        user, created = User.objects.get_or_create(username = request.data['username'])
        if created:
            user.set_password(password)
            group = Group.objects.get(name = request.data['usertype'])
            group.user_set.add(user)
            user.save()
            scrum_user = ScrumUser(user=user, nickname=request.data['full_name'])
            scrum_user.save()
            return JsonResponse({'message':'User Created Successfully'})
        else:
            return JsonResponse({'message': 'Error: Username Already Exists.'})

class ScrumGoalViewSet(viewsets.ModelViewSet):
    '''
    API endpoint that allows groups to be viewed or edited
    '''
    queryset = ScrumyGoals.objects.all()
    serializer_class = ScrumGoalSerializer

    def create(self,request):
        username = request.data['username']
        password = request.data['password']


        user = authenticate(request, username=username, password=password)
        if user is not None:
            name_goal = request.data['name']
            id_goal = request.data['id']
            group_name = user.groups.all()[0].name
            status_start = GoalStatus.objects.get(pk=1)
            if group_name == 'Admin':
                status_start = GoalStatus.objects.get(pk=3)
            elif group_name == 'Quality Assurance':
                status_start = GoalStatus.objects.get(pk=2)
            goal = ScrumyGoals(user=user.scrumuser, goal_id= id_goal, goal_name=name_goal,goal_status=status_start)
            goal.save()
            return JsonResponse({'exit':0, 'message':'Goal added', 'data': filtered_users()})
        else:
            return JsonResponse({'exit':1, 'message':'Not Logged In! Please Login First'})
    
    def patch(self, request):
            goals_id = request.data['goal_id']
            to_id = request.data['to_id']
            user = authenticate(request, username=request.data['username'], password=request.data['password'])
            if to_id == 5:
                if user.groups.all()[0].name == 'Developer':
                    if user != ScrumyGoals.objects.get(id = goals_id).user:
                        return JsonResponse({'message':'Permission Denied: Unauthorized Deletion of Goal', 'data':filtered_users()})          
                del_goal = ScrumyGoals.objects.get(id = goals_id)
                del_goal.visible = False
                print (goals_id)
                del_goal.save()
                return JsonResponse({'message':'Goal Removed Successfully', 'data':filtered_users()})
            else:
                goal_item = ScrumyGoals.objects.get(id = goals_id)

                group = user.groups.all()[0].name
                from_allowed = []
                to_allowed = []
                    
                if group == 'Developer':
                    if user != goal_item.user:
                        return JsonResponse({'message':'Permission Denied: Unauthorized Movement of Goal', 'data':filtered_users()})
                           
                if group == 'Owner':
                    from_allowed = [1, 2, 3, 4]
                    to_allowed = [1, 2, 3, 4]
                elif group == 'Admin':
                    from_allowed = [2, 3]
                    to_allowed = [1, 2]
                elif group == 'Developer':
                    from_allowed = [1, 2]
                    to_allowed = [1, 2]
                # elif group == 'Quality Analyst':
                #     from_allowed = [3, 4]

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Add Goal </title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Add Goal">
</form>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>Sorry! You can't move other users goal</p>
<p>Back to <a href="{% url 'samsonadejoroscrumy:home' %}"> Home</a></p>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>You can not move goal from Daily Target. You can only move from Verify to Done. And Verify back to Daily and Weekly.</p>
<p>Back to <a href="{% url 'samsonadejoroscrumy:home' %}">Home</a></p>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/exception.html
<h1>{{ error_message }}</h1>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/goalsuccess.html
<h1>{{ success2 }}</h1>
<a href="{% url 'samsonadejoroscrumy:add_goal' %}"> <h2> You wanna add more? </h2> </a>
<a href="{% url 'samsonadejoroscrumy:home' %}"> <h2> Go back to home</h2> </a>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/home.html
<style>
table, th, td {
  border: 1px solid black;
}
a{
margin-top: 20px;
text-decoration: none;
}
a:hover{
color: blue;
}
form{
   padding-top: 20px;
   }
</style>
<!doctype html>
<html>
<head><title> Homepage </title></head>
<body>
<h2> Welcome back:  {{ current_user }} -- {{ group }}  </h2>
<table>
    <colgroup span="5"></colgroup>
    <tr>
        <th>User</th>
        <th colspan="1">Weekly Goals</th>
        <th colspan="1">Daily Target</th>
        <th colspan="1">Verify Goals</th>
        <th colspan="1">Done Goals</th>

    </tr>

    {% if user %}
    {% for username in user %}
    <tr>
        <td rowspan="1">
            <p> {{username}}</p>

        </td>
        {% if weekly_goal %}
            <td rowspan="1">
                {%for goals in weekly_goal %}
                    {% if goals.user == username %}
                <p> <i>Goal ID:</i> {{goals.goal_id}} &nbsp; &nbsp; <i>Goal Name:</i> <a href="{% url 'samsonadejoroscrumy:movegoal' goal_id=goals.goal_id %}" > {{goals.goal_name}} </a>
                    {% endif %}
                {% endfor %}

            </td>
        {% else %}
        <td>There is No Goal</td>
        {% endif %}

        {% if daily_goal %}
            <td rowspan="1">
                {% for goals in daily_goal %}
                    {% if goals.user == username %}

                <p> <i>Goal ID:</i> {{goals.goal_id}} &nbsp; &nbsp; <i>Goal Name:</i> <a href="{% url 'samsonadejoroscrumy:movegoal' goal_id=goals.goal_id %}" >  {{goals.goal_name}} </a></p>
                    {% endif %}
                {% endfor %}

            </td>
        {% else %}
        <td>There is No Goal</td>
        {% endif %}

        {% if verify_goal %}
            <td rowspan="1">
                {% for goals in verify_goal %}

                    {% if goals.user == username %}
                <p> <i>Goal ID:</i> {{goals.goal_id}} &nbsp; &nbsp; <i>Goal Name:</i> <a href="{% url 'samsonadejoroscrumy:movegoal' goal_id=goals.goal_id %}" > {{goals.goal_name}} </a> </p>
                    {% endif %}
                {% endfor %}

            </td>
        {% else %}
        <td>There is No Goal</td>
        {% endif %}

        {% if done_goal %}
            <td rowspan="1">
                {% for goals in done_goal %}
                    {% if goals.user == username %}
                <p> <i>Goal ID:</i> {{goals.goal_id}} &nbsp; &nbsp; <i>Goal Name:</i>  <a href="{% url 'samsonadejoroscrumy:movegoal' goal_id=goals.goal_id %}" >  {{goals.goal_name}} </a></p>
                    {% endif %}
                {% endfor %}
            </td>
        {% else %}
        <td>There is No Goal</td>
        {% endif %}

    </tr>
    {% endfor %}
    {% endif %}

</table>

<a href="{% url 'samsonadejoroscrumy:add_goal' %}"> <h2> Add Goals Here </h2> </a>
<a href="{% url 'samsonadejoroscrumy:index' %}"  target="_blank"> <h2>Sign up here</h2> </a>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Goals Details</title>
</head>

<body>
    <h4> Currently Logged in as {{current_user}} - <span class="group">{{group}}</span></h4>
    <div class="goaldetail">
        <h2>GOAL DETAILS</h2>
        <p>Goal ID: {{goals.goal_id}}</p>
        <p>Goal Name: {{goals}}</p>
        <p>Goal Status: {{goals.goal_status}}</p>

    </div>


    {% if form.errors %}
    <p>
        <strong> All Fields are requireds, please try again.</strong>
    </p>
    {% endif %}


        <form action="" method="POST">
            {% csrf_token %}
            <legend>Move Goal Form</legend>
            {{ form.as_p }}
                <button type="submit">Move Goal</button>
        </form>
</body>

</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/movegoalsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Move Goal Success Page</title>
</head>
<body>
<p>Goal has been moved successfully</p>
<p>Back to <a href="{% url 'samsonadejoroscrumy:home' %}">Home</a></p>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/signup.html
<style>
label{
	display: block;
	border: 2px;
	padding-bottom: 10px;
	margin-top: 10px;
}
input[type="submit"]{
display: block;
margin-top: 20px;
}
</style>


<!DOCTYPE html>
<html>
<head> <title> Sign Up </title></head>
<body>
<form  method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

Django/myscrumy/samsonadejoroscrumy/templates/samsonadejoroscrumy/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Account Creation Success Page</title>
</head>
<body>
<h1> {{success}} </h1>
<a href="http://127.0.0.1:8000/samsonadejoroscrumy/accounts/login/"> Login right away </a>
</body>
</html>



<!-- nu83dUmfHPoecoAdj5 -->